### ISSUE TITLE
Foxbox panics intermittently during the interaction with UI app

### ISSUE THREAD

**Issue by nojunpark** [fxbox/foxbox#350]
Gives below backtrace.  will update when reproduce steps are found.

```
thread '<unnamed>' panicked at 'arithmetic operation overflowed', ../src/libcore/cell.rs:515
note: Run with `RUST_BACKTRACE=1` for a backtrace.
[2016-04-12 22:03:29.982] INFO  Server responded with: {"status" : "registered"}
[2016-04-12 22:03:29.982] INFO  Registering ip '192.168.1.134' at 'https://knilxof.org:5300/v1/dns/org/knilxof/box/a5226d811c399ce2c1de1e7c6d9d1e6afb19b677/local'
thread '<unnamed>' panicked at 'arithmetic operation overflowed', ../src/libcore/cell.rs:515
thread '<unnamed>' panicked at 'arithmetic operation overflowed', ../src/libcore/cell.rs:515
stack backtrace:
   1:        0x10bbc4708 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
   2:        0x10bbc89e5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
   3:        0x10bbc861e - std::panicking::default_hook::h08ad3bb09872855b
   4:        0x10bbb3026 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
   5:        0x10bbb3ebe - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
   6:        0x10bbc39d7 - rust_begin_unwind
   7:        0x10bbef8b0 - core::panicking::panic_fmt::ha6b3c19493c123b3
   8:        0x10bbefbac - core::panicking::panic::h188c6c6a0fe5463c
   9:        0x10b79ec21 - _<cell..BorrowRef<'b> as ops..Drop>::drop::hef6aad621b67561e
  10:        0x10b79eb8c - std..cell..BorrowRef<'static>::drop.16566::h3973b237b356dbdb
  11:        0x10b803c99 - std..cell..Ref<'static, backend..GetterData>::drop.18276::h9df6058917be223e
  12:        0x10b8552e9 - foxbox_taxonomy::backend::State::with_channels::_$u7b$$u7b$closure$u7d$$u7d$::h575c1ceb381abc8d
  13:        0x10b855218 - core::iter::Iterator::any::haced6d477263ef37
  14:        0x10b855059 - foxbox_taxonomy::backend::State::with_channels::hceb916a37f1d90c8
  15:        0x10b8533e3 - foxbox_taxonomy::backend::State::prepare_fetch_values::h65f57e985fd3e119
  16:        0x10b89ca98 - _<manager..AdapterManager as api..API>::fetch_values::hf4ed698201e97ecb
  17:        0x10b2da997 - _<taxonomy_router..TaxonomyRouter as iron..Handler>::handle::hc61bc9cc3195153d
  18:        0x10ba32ea6 - _<Box<middleware..Handler $u2b$$u20$$u27$static$GT$$u20$as$u20$middleware..Handler$GT$::handle::h4d55ba6101989e03
  19:        0x10b5458c0 - _<auth_middleware..AuthHandler<H> as iron..Handler>::handle::h0f11e8dc9ffdd9e3
  20:        0x10ba32ea6 - _<Box<middleware..Handler $u2b$$u20$$u27$static$GT$$u20$as$u20$middleware..Handler$GT$::handle::h4d55ba6101989e03
  21:        0x10ba32b84 - iron::middleware::Chain::continue_from_handler::h5d42ad1ba52d3cb4
  22:        0x10ba2d0a7 - iron::middleware::Chain::continue_from_before::h86190dbe386feacf
  23:        0x10ba2d035 - _<middleware..Chain as middleware..Handler>::handle::hba8072419761da4c
  24:        0x10ba32ea6 - _<Box<middleware..Handler $u2b$$u20$$u27$static$GT$$u20$as$u20$middleware..Handler$GT$::handle::h4d55ba6101989e03
  25:        0x10b40f62d - _<mount..Mount as iron..Handler>::handle::h4f626927c6134814
  26:        0x10ba32ea6 - _<Box<middleware..Handler $u2b$$u20$$u27$static$GT$$u20$as$u20$middleware..Handler$GT$::handle::h4d55ba6101989e03
  27:        0x10ba32b84 - iron::middleware::Chain::continue_from_handler::h5d42ad1ba52d3cb4
  28:        0x10ba2d0a7 - iron::middleware::Chain::continue_from_before::h86190dbe386feacf
  29:        0x10ba2d035 - _<middleware..Chain as middleware..Handler>::handle::hba8072419761da4c
  30:        0x10b2ff747 - _<iron..Iron<H> as hyper..server..Handler>::handle::h44fe913a543a09b3
  31:        0x10b31ee7e - _<hyper..server..Worker<H>>::keep_alive_loop::hf7f525cec7b7b2fd
  32:        0x10b31bd60 - _<hyper..server..Worker<H>>::handle_connection::hd9d538905d8e220d
  33:        0x10b31aff7 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::ha754b16afecc4b83
  34:        0x10b324d95 - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::he930c49c34b4a269
  35:        0x10b32465f - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfba916e11ca63ec7
  36:        0x10b3245e9 - std::sys_common::unwind::try::try_fn::h1e23df2aaac99e5b
  37:        0x10bbc396b - __rust_try
  38:        0x10bbc38f3 - std::sys_common::unwind::inner_try::h4e97625a08807651
  39:        0x10b324552 - std::sys_common::unwind::try::h0a5bd62b8e1007e7
  40:        0x10b32437e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h892f93ac5841f36b
  41:        0x10b325240 - _<F as std..boxed..FnBox<A>>::call_box::hec87fc56fdb7a0a5
  42:        0x10bbc7c38 - std::sys::thread::Thread::new::thread_start::h74af400293164137
  43:     0x7fff9519899c - _pthread_body
  44:     0x7fff95198919 - _pthread_start
thread panicked while panicking. aborting.
error: An unknown error occurred
```

**Comment by mcav** [comment]
The response to [a similar Rust user's issue](https://github.com/rust-lang/rust/issues/27225) points to problems with code implenting `unsafe impl Send` as well as `Arc<RefCell>`. I wonder if our use of `Arc<SubCell>` in `backend.rs` is a similar case.

**Comment by Yoric** [comment]
The key frames seem to be

```
9: 0x10b79ec21 - _ as ops..Drop>::drop::hef6aad621b67561e
10: 0x10b79eb8c - std..cell..BorrowRef<'static>::drop.16566::h3973b237b356dbdb
11: 0x10b803c99 - std..cell..Ref<'static, backend..GetterData>::drop.18276::h9df6058917be223e
12: 0x10b8552e9 - foxbox_taxonomy::backend::State::with_channels::$u7b$$u7b$closure$u7d$$u7d$::h575c1ceb381abc8d
13: 0x10b855218 - core::iter::Iterator::any::haced6d477263ef37
```

**Update** Yes, @mcav, you're almost certainly right.
I'll take another look at `State::with_channels` and see if I can find something wrong.

**Comment by Yoric** [comment]
@npark-mozilla Ok, I believe I have fixed the issue. You'll need to `cargo update` to grab the latest version of `sublock`.

@mcav You were entirely right.

**Comment by Yoric** [comment]
@npark-mozilla Can you confirm that the issue is solved for you?

**Comment by nojunpark** [comment]
@Yoric both isabel and I no longer see this issue after cargo update. thanks!
