### ISSUE TITLE
Sometimes, foxbox needs to run as root.

### ISSUE THREAD

**Issue by dhylands** [fxbox/foxbox#363]
Today, when I tried to run foxbox, (I tried with and without --disable-tls and also tried removing the certs directory, all with the same effect):

```
2080 >RUST_BACKTRACE=1 cargo run -- --disable-tls
     Running `target/debug/foxbox --disable-tls`
thread '<main>' panicked at 'Failed set host name: Access denied (code -20)', /home/dhylands/.multirust/toolchains/nightly-2016-04-10/cargo/git/checkouts/multicast-dns-d51af2fa146824d6/a6e4bcc/src/adapters/avahi/adapter.rs:346
stack backtrace:
   1:     0x7ff3d349fe80 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
   2:     0x7ff3d34a5fab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
   3:     0x7ff3d34a5c33 - std::panicking::default_hook::h08ad3bb09872855b
   4:     0x7ff3d348e17f - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
   5:     0x7ff3d348f1c8 - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
   6:     0x7ff3d2d49f38 - _<adapters..avahi..adapter..AvahiAdapter as adapters..adapter..HostAdapter>::set_name::h2bed60aa1ab07b54
                        at /home/work/fxbox/foxbox/<std macros>:8
   7:     0x7ff3d2d4ec0f - multicast_dns::host::host_manager::HostManager::set_name::h8b6b157855e59ff3
                        at /home/dhylands/.multirust/toolchains/nightly-2016-04-10/cargo/git/checkouts/multicast-dns-d51af2fa146824d6/a6e4bcc/src/host/host_manager.rs:21
   8:     0x7ff3d2772fa6 - foxbox::update_hostname::hc21239e54baa1f82
                        at src/main.rs:167
   9:     0x7ff3d27737ce - foxbox::main::h000728ee4216cb83
                        at src/main.rs:241
  10:     0x7ff3d34a5874 - std::sys_common::unwind::try::try_fn::hfe4b14ce00a3f42f
  11:     0x7ff3d349f05b - __rust_try
  12:     0x7ff3d34a52bb - std::rt::lang_start::h12d9b3310b48a726
  13:     0x7ff3d279bed9 - main
  14:     0x7ff3d0a08ec4 - __libc_start_main
  15:     0x7ff3d276ecc6 - <unknown>
  16:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/foxbox --disable-tls` (exit code: 101)
```

In order to get it to run, I had to run it as root. Then I was able to run it as non-root.

However, running it as means that any files produced were owned by root (so it created a new certs directory).

This feels problematic to me.

Tagging @samgiles since he added the code which calls update_hostname.

**Comment by JohanLorenzo** [comment]
I got the same issue, yesterday. @azasypkin helped me out on it. Let me update the README with a solution.

**Comment by dhylands** [comment]
So I think that 2 things should be done then.

1 - We shouldn't crash, but should catch the error properly and report it properly
2 - If we need to be a member of netdev group, then we should do that check and print a warning if we're not a member of that group.

**Comment by dhylands** [comment]
Similarly, we need to be a member of the dialout group in order to open the serial port for the zwave dongle.

**Comment by azasypkin** [comment]
> We shouldn't crash, but should catch the error properly and report it properly

Yeah, I've filed https://github.com/fxbox/multicast-dns/issues/6
